# === DATABASE CONFIG ===
spring.datasource.url=jdbc:mysql://monorail.proxy.rlwy.net:3306/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=RhxdfjlnjtYELCZAoKfZWgaqpDIkAOnK

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
